name: ci

on:
  push:
    branches:
      - "master"
    tags:
      - 'v*'
    paths:
      - app/**
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
env:
  IMAGE: "tpneal/kubetoy"

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      kubetoy_image_digest: ${{ steps.setdigest.outputs.digestvalue }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            #type=semver,pattern={{major}}.{{minor}}
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          install: true
      - name: Build and push
        id: push
        uses: docker/build-push-action@v5
        with:
          context: ./app
          tags: ${{ steps.meta.outputs.tags }}
          # For pull requests, export results to the build cache.
          # Otherwise, push to a registry.
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry,push=true' }}
      - name: set-digest
        id: setdigest
        run: echo "digestvalue=${{ steps.push.outputs.digest }}" >> "$GITHUB_OUTPUT"

  update-kustomization-yaml:
    name: "Update Kustomization.yaml File"
    needs: "docker"
    runs-on: ubuntu-latest
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v4
        with:
          token:  ${{ secrets.GH_PAT }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            #type=semver,pattern={{major}}.{{minor}}
      - name: "Update Deployment Image Tag"
        working-directory: "deployment/all-in-one"
        run: |
          kustomize edit set image ${{ env.IMAGE }}@${{ needs.docker.outputs.kubetoy_image_digest }}
      - name: "Commit Updated Image Tag To GitHub Repository"
        run: |
          git config --global user.name "tpneal"
          git config --global user.email "thomas.neal@hcl.com"
          git commit -am "Set image tag to ${{ env.IMAGE }}@${{ needs.docker.outputs.kubetoy_image_digest }}"
          git push
